### ISSUE TITLE
Function definitions and Function prototypes are conflicting...

### ISSUE THREAD

**Issue by AndrejValand** [MatrixOrbital/EVE2-Library#4]
Two Examples of many in the library...

Example 1:
void FT81x_Init(int display, int board, int touch)
void FT81x_Init(void)
…

Example 2:
void Cmd_AnimDrawFrame(uint32_t addr, uint16_t Xpos, uint16_t Ypos, uint8_t Frame)
void Cmd_AnimDrawFrame(int16_t x, int16_t y, uint32_t aoptr, uint32_t frame);
…

**Comment by chadpham75** [comment]
Using Eve2_81x.h/.c files in https://github.com/MatrixOrbital/Basic-EVE-Demo-STM32 to have a better result.  You can compare the two files from EVE2-Library and Basic-EVE-Demo-STM32.  However, the STM32 .ioc has some mismatch with source file main.c so watch out for it.

**Comment by matrixraym** [comment]
I have updated the library to the latest internal code drop
